DiscompileIEnumerator:
	mono-csc DiscompileIEnumerator.cs && mono ./DiscompileIEnumerator.exe; monodis DiscompileIEnumerator.exe > DiscompileIEnumerator.il

DebuggerHidden:
	mono-csc DebuggerHidden.cs && mono ./DebuggerHidden.exe; monodis DebuggerHidden.exe > DebuggerHidden.il

clean:
	rm *.exe
